### ISSUE TITLE
Customize command shortcuts

### ISSUE THREAD

**Issue by graphixillusion** [bettercallshao/kwt#48]
Hi there. I wonder if it's possible to add an option to customize the keyboard shortcuts for the custom commands in the yaml. Actually the program auto chooses the first letter of the name and if the letter is already taken by another command it will chooses the second one and so on. It would be greate to have an option which allows to customize it, even to choose multiple letters as shortcut. For example: i use it very much with scoop. The first s of the name "scoop" is already taken by the program for the start command so it will auto chooses the second letter "c". With the ability to customize it using multiple letters i could configure it as "sc" for example so all the scoop's commands starts with 

kwt sc ...

**Comment by bettercallshao** [comment]
Hi there~ Thank you for submitting an issue and making me feel important!

I agree it's reasonable to specify a arbitrary length shortcut (or multiple arbitrary length aliases) as part of the yaml. If multiple letters are allowed in a shorthand, `kwt shorthands` feature may run into collisions, but I think it's ok since it's not a fatal error and we can leave it to the user to solve the collisions.

I also sometimes find that the automatically chosen shortcuts inconvenient, I workaround it by prefixing the "action name" with what I want the shortcut letter to be. In your case as a workaround, you can name your yaml / action to `sc` (instead of `scoop`) while I add the feature.

**Comment by bettercallshao** [comment]
Try https://github.com/bettercallshao/kwt/releases/tag/v0.6.6 

you can add a list of aliases in a menu, action, or param. Letter s is also available. e.g.

```
name: scoop
aliases:
- s
actions:
...
```

**Comment by graphixillusion** [comment]
Works great, thank you.
